In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4,5,6,7,8,9,10]);print(a)
al = [1,33,44,665];print(al)
print(f'{"object type":<15}{type(a)}')

[ 1  2  3  4  5  6  7  8  9 10]
[1, 33, 44, 665]
object type    <class 'numpy.ndarray'>


In [22]:
al = np.array([]);
print(al.shape,al.ndim,al.size)


(0,) 1 0


In [23]:
# filling arrays with spacified values
a_zeros = np.zeros((3,3));print(a_zeros)
a_ones = np.ones((2,4));print(a_ones)
a_full = np.full((3,5),7);print(a_full)
print("Identity Matrix")
a_eye = np.eye(3);print(a_eye) # identity matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#Filling array with random floats : in the half open interval [0.0, 1.0)
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')
print(np.random.choice(range(0,7)))
print(np.random.choice(['hamburger','pizza','sandwich','pancake']))

[[[0.39198833 0.2957196  0.64228652 0.46626636]
  [0.55591378 0.16694196 0.82213839 0.61905614]
  [0.53617992 0.48472725 0.13666729 0.32494552]]

 [[0.75130312 0.27503385 0.29945866 0.12799674]
  [0.78762158 0.47948564 0.42913413 0.64512623]
  [0.05805303 0.26672882 0.34229394 0.07716849]]]
float64
2
pancake


In [25]:
#Making an array with arrange  same interval
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [26]:
h = np.arange(5,21,2.5)
print(h)
print(np.arange(1,21).reshape(2,10))

[ 5.   7.5 10.  12.5 15.  17.5 20. ]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [27]:
print(np.reshape(np.arange(1,21),(2,10))) #nested function

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [28]:
a_ss = np.linspace(0,1,5)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}' )

[0.   0.25 0.5  0.75 1.  ]
(5,)
5


Arrays Operations and BroadCasting

In [29]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape,xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [30]:
print(np.add(xa,xb))
print(np.multiply(xa,xb))
print(np.subtract(xa,xb))
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 3  8]
 [15 24]
 [35 48]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [31]:
#inner product matrix
xc = np.ones((2,3))
print(xc,xc.shape,xc.ndim)
print(xa.dot(xc))
print(np.dot(xa,xc))


[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) 2
[[ 3.  3.  3.]
 [ 7.  7.  7.]
 [11. 11. 11.]]
[[ 3.  3.  3.]
 [ 7.  7.  7.]
 [11. 11. 11.]]


In [32]:
# inner Product of matrix
xd = np.array([[1,2],[1,2]]),
print(xd)
print(np.dot(xa,xd))

(array([[1, 2],
       [1, 2]]),)
[[[ 3  6]]

 [[ 7 14]]

 [[11 22]]]


In [33]:
# Transpose of matrix
print(xa)
print("----")
print(xa.T)

[[1 2]
 [3 4]
 [5 6]]
----
[[1 3 5]
 [2 4 6]]


In [34]:
# Broadcasting : Arithmetic operations between arrays of different shapes arrays
# the smaller array is broadcast across the larger array so that they have compatible shapes
print(xa+3)
print(xa)
xa += 3
print(xa)

[[4 5]
 [6 7]
 [8 9]]
[[1 2]
 [3 4]
 [5 6]]
[[4 5]
 [6 7]
 [8 9]]


Slicing and flattening arrays

In [36]:
karray = np.arange(21).reshape(3,7);
print(karray,karray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] (3, 7)


In [38]:
print(karray[0])
print(karray[:2])
print(karray[0,:4])

[0 1 2 3 4 5 6]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[0 1 2 3]


In [43]:
#double indexing
print(karray[[0,]])
print(karray[:,[0,2]])

[[0 1 2 3 4 5 6]]
[[ 0  2]
 [ 7  9]
 [14 16]]


In [46]:
#flattening an array
fkarray = karray.flatten()
print(fkarray)
##both work same
fkarray2 = karray.reshape(21)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [47]:
# summary statistics
karray = np.arange(2,23).reshape(3,7)
print(karray)


[[ 2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22]]


In [48]:
print(karray.sum(),karray.min(),karray.max(),karray.mean(),karray.std(),karray.var())

252 2 22 12.0 6.0553007081949835 36.666666666666664


In [49]:
print(karray.mean(axis=0),karray.mean(axis=1))

[ 9. 10. 11. 12. 13. 14. 15.] [ 5. 12. 19.]


In [50]:
print(karray.argmax(),karray.argmin())
print(karray.argmax(axis=0),karray.argmin(axis=1))

20 0
[2 2 2 2 2 2 2] [0 0 0]


In [54]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A.size)

6
