In [1]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9,10]);print(a)
al = [1,33,44,665];print(al)
print(f'{"object type":<15}{type(a)}')

[ 1  2  3  4  5  6  7  8  9 10]
[1, 33, 44, 665]
object type    <class 'numpy.ndarray'>


In [8]:
al = np.array([]);
print(al.shape,al.ndim,al.size)


(0,) 1 0


In [10]:
# filling arrays with spacified values
a_zeros = np.zeros((3,3));print(a_zeros)
a_ones = np.ones((2,4));print(a_ones)
a_full = np.full((3,5),7);print(a_full)
print("Identity Matrix")
a_eye = np.eye(3);print(a_eye) # identity matrix

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Identity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Filling array with random floats : in the half open interval [0.0, 1.0)
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')
print(np.random.choice(range(0,7)))
print(np.random.choice(['hamburger','pizza','sandwich','pancake']))

[[[0.81201204 0.89291137 0.30745053 0.1112661 ]
  [0.38478877 0.63381883 0.78442478 0.96980618]
  [0.78970257 0.52309935 0.97526031 0.0117612 ]]

 [[0.40374184 0.09143901 0.3141708  0.58036363]
  [0.44529826 0.34174982 0.40854627 0.8300216 ]
  [0.01975539 0.42969131 0.20387417 0.16461895]]]
float64
1
sandwich


In [29]:
#Making an array with arrange  same interval
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [31]:
h = np.arange(5,21,2.5)
print(h)
print(np.arange(1,21).reshape(2,10))

[ 5.   7.5 10.  12.5 15.  17.5 20. ]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [32]:
print(np.reshape(np.arange(1,21),(2,10))) #nested function

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [33]:
a_ss = np.linspace(0,1,5)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}' )

[0.   0.25 0.5  0.75 1.  ]
(5,)
5


Arrays Operations and BroadCasting

In [3]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape,xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [35]:
print(np.add(xa,xb))
print(np.multiply(xa,xb))
print(np.subtract(xa,xb))
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 3  8]
 [15 24]
 [35 48]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [4]:
#inner product matrix
xc = np.ones((2,3))
print(xc,xc.shape,xc.ndim)
print(xa.dot(xc))
print(np.dot(xa,xc))


[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) 2
[[ 3.  3.  3.]
 [ 7.  7.  7.]
 [11. 11. 11.]]
[[ 3.  3.  3.]
 [ 7.  7.  7.]
 [11. 11. 11.]]


In [7]:
# inner Product of matrix
xd = np.array([[1,2],[1,2]]),
print(xd)
print(np.dot(xa,xd))

(array([[1, 2],
       [1, 2]]),)
[[[ 3  6]]

 [[ 7 14]]

 [[11 22]]]


In [9]:
# Transpose of matrix
print(xa)
print("----")
print(xa.T)

[[1 2]
 [3 4]
 [5 6]]
----
[[1 3 5]
 [2 4 6]]
